# Generated by Django 5.2 on 2025-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuResto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(default='-')),
                ('image_menu', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('category', models.CharField(max_length=100)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
                ('menu_status', models.CharField(choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada')], default='Ada', max_length=15)),
            ],
        ),
    ]
