# Generated by Django 5.2 on 2025-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_menuresto_statusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuresto',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15),
        ),
    ]
