# Generated by Django 5.2 on 2025-05-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_menuresto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuresto',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_of_menu', to='pos_app.statusmodel'),
        ),
    ]
