# Generated by Django 5.2 on 2025-05-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_alter_menuresto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmodel',
            name='menu_status',
        ),
        migrations.AddField(
            model_name='menuresto',
            name='menu_status',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Tidak Ada', 'Tidak Ada')], default='Ada', max_length=15),
        ),
        migrations.AddField(
            model_name='menuresto',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_menu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuresto',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_menu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menuresto',
            name='image_menu',
            field=models.ImageField(blank=True, default='default_images/empt.jpg', null=True, upload_to='menu_images/'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_category', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='menuresto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_menu', to='pos_app.category'),
        ),
    ]
