# Generated by Django 5.2 on 2025-05-10 19:59

import pos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_remove_statusmodel_menu_status_menuresto_menu_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuresto',
            name='code',
            field=models.CharField(default=pos_app.models.increment_menu_resto_code, editable=False, max_length=20),
        ),
    ]
